SELECT DISTINCT '2023-11-23'::date                       as FILE_DATE,
                'LA'                                     as STATE_CODE,
                C.COUNTY_NAME                           as COUNTY_CODE,
                REGISTRATION_NUMBER                      AS VOTER_ID,
                PERSONAL_NAME_PREFIX                     AS PREFIX,
                PERSONAL_FIRST_NAME                      AS FIRST_NAME,
                PERSONAL_MIDDLE_NAME                     AS MIDDLE_NAME,
                PERSONAL_LAST_NAME                       AS LAST_NAME,
                PERSONAL_NAME_SUFFIX                     AS NAME_SUFFIX,
                {{ target.schema }}.MERGE_ADDRESS_ELEMENTS([
                    RESIDENCE_HOUSE_NUMBER,
                    RESIDENCE_HOUSE_FRACTION,
                    RESIDENCE_STREET_DIRECTION,
                    RESIDENCE_STREET_NAME
                    ])                                   AS RESIDENCE_ADDRESS_LINE_1,
                {{ target.schema }}.MERGE_ADDRESS_ELEMENTS([
                    RESIDENCE_APARTMENT_NUMBER
                    ])                                   AS RESIDENCE_ADDRESS_LINE_2,
                RESIDENCE_CITY                           AS RESIDENCE_ADDRESS_CITY,
                COALESCE(RESIDENCE_STATE, 'LA')          AS RESIDENCE_ADDRESS_STATE,
                RESIDENCE_ZIPCODE5                       AS RESIDENCE_ADDRESS_ZIPCODE,
                'USA'                                    AS RESIDENCE_ADDRESS_COUNTRY,
                NULL                                     AS BIRTH_YEAR,
                NULL                                     AS BIRTH_MONTH,
                NULL                                     AS BIRTH_DATE,
                REGISTRATION_VOTER_STATUS                as VOTER_STATUS,
                TO_DATE(REGISTRATION_DATE, 'MM/DD/YYYY') AS REGISTRATION_DATE,
                TO_DATE(LAST_VOTED, 'MM/DD/YYYY')        AS LAST_VOTED_DATE,
                REGISTRATION_POLITICAL_PARTY_CODE        AS LAST_PARTY_VOTED,
                JURISDICTION_DISTRICT_CONGRESSIONAL      AS CONGRESSIONAL_DISTRICT,
                JURISDICTION_DISTRICT_SENATE             AS STATE_SENATE_DISTRICT,
                JURISDICTION_DISTRICT_REPRESENTATIVE     AS STATE_HOUSE_DISTRICT,
                JURISDICTION_DISTRICT_DISTRICT_COURT     AS JUDICIAL_DISTRICT,
                NULL                                     AS COUNTY_COMMISSION_DISTRICT,
                JURISDICTION_DISTRICT_SCHOOL_BOARD       AS SCHOOL_BOARD_DISTRICT,
                NULL                                     AS CITY_COUNCIL_DISTRICT,
                JURISDICTION_PRECINCT                    AS COUNTY_PRECINCT,
                NULL                                     AS MUNICIPAL_PRECINCT,
                NULL                                     AS RACE,
                NULL                                     AS GENDER,
                MAIL_ADDRESS1                            AS MAILING_ADDRESS_LINE_1,
                MAIL_ADDRESS2                            AS MAILING_ADDRESS_LINE_2,
                NULL                                     AS MAILING_LINE_3,
                MAIL_CITY                                AS MAILING_CITY,
                MAIL_STATE                               AS MAILING_STATE,
                MAIL_ZIPCODE5                            AS MAILING_ZIPCODE,
                MAIL_COUNTRY                             AS MAILING_COUNTRY
FROM {{ source('raw', 'LOUISIANA_RAW_DATA_2023_11_23') }} V
         INNER JOIN {{ ref("louisiana_counties") }} C ON V.JURISDICTION_PARISH = C.COUNTY_ID
