SELECT '2023-09-25'::date                               as FILE_DATE,
       'OH'                                             as STATE_CODE,
       COUNTY.county_name                               as COUNTY_CODE,
       VOTERS.SOS_VOTERID                               AS VOTER_ID,
       NULL                                             AS PREFIX,
       VOTERS.FIRST_NAME                                AS FIRST_NAME,
       VOTERS.MIDDLE_NAME                               AS MIDDLE_NAME,
       VOTERS.LAST_NAME                                 AS LAST_NAME,
       VOTERS.SUFFIX                                    AS NAME_SUFFIX,
       RESIDENTIAL_ADDRESS1                             AS RESIDENCE_ADDRESS_LINE_1,
       RESIDENTIAL_SECONDARY_ADDR                       AS RESIDENCE_ADDRESS_LINE_2,
       RESIDENTIAL_CITY                                 AS RESIDENCE_ADDRESS_CITY,
       COALESCE(RESIDENTIAL_STATE, 'OH')                AS RESIDENCE_ADDRESS_STATE,
       RESIDENTIAL_ZIP                                  AS RESIDENCE_ADDRESS_ZIPCODE,
       COALESCE(RESIDENTIAL_COUNTRY, 'USA')             AS RESIDENCE_ADDRESS_COUNTRY,
       YEAR(TO_DATE(DATE_OF_BIRTH, 'YYYY-MM-DD'))       AS BIRTH_YEAR,
       MONTH(TO_DATE(DATE_OF_BIRTH, 'YYYY-MM-DD'))      AS BIRTH_MONTH,
       DAYOFMONTH(TO_DATE(DATE_OF_BIRTH, 'YYYY-MM-DD')) AS BIRTH_DATE,
       CASE
           WHEN VOTER_STATUS = 'ACTIVE' THEN 'A'
           WHEN VOTER_STATUS = 'CONFIRMATION' THEN 'CON'
           ELSE NULL
           END                                          as VOTER_STATUS,
       TO_DATE(REGISTRATION_DATE, 'YYYY-MM-DD')         AS REGISTRATION_DATE,
       NULL                                             AS LAST_VOTED_DATE,
       PARTY_AFFILIATION                                AS LAST_PARTY_VOTED,
       CONGRESSIONAL_DISTRICT                           AS CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT                            AS STATE_SENATE_DISTRICT,
       STATE_REPRESENTATIVE_DISTRICT                    AS STATE_HOUSE_DISTRICT,
       NULL                                             AS JUDICIAL_DISTRICT,
       NULL                                             AS COUNTY_COMMISSION_DISTRICT,
       CITY_SCHOOL_DISTRICT                             AS SCHOOL_BOARD_DISTRICT,
       NULL                                             AS CITY_COUNCIL_DISTRICT,
       PRECINCT_NAME                                    AS COUNTY_PRECINCT,
       NULL                                             AS MUNICIPAL_PRECINCT,
       NULL                                             AS RACE,
       NULL                                             AS GENDER,
       MAILING_ADDRESS1                                 AS MAILING_ADDRESS_LINE_1,
       MAILING_SECONDARY_ADDRESS                        AS MAILING_ADDRESS_LINE_2,
       NULL                                             AS MAILING_LINE_3,
       MAILING_CITY                                     AS MAILING_CITY,
       MAILING_STATE                                    AS MAILING_STATE,
       MAILING_ZIP                                      AS MAILING_ZIPCODE,
       MAILING_COUNTRY                                  AS MAILING_COUNTRY
FROM {{ source('raw', 'OHIO_VOTERS_2023_09_25') }} VOTERS
         INNER JOIN {{ ref("ohio_counties") }} COUNTY ON VOTERS.COUNTY_NUMBER = COUNTY.county_id