version: 2
sources:
  - name: raw
    description: This is the raw voter data that is loaded into tables
    tables:
      - name: ALABAMA_VOTERS_2024_01_15
      - name: ALASKA_VOTERS_2023_11_13
      - name: ARIZONA_VOTERS_2023_11_05
      - name: ARKANSAS_VOTERS_2023_09_01
      - name: ARKANSAS_VOTER_HISTORY_2023_09_01
      - name: CALIFORNIA_VOTERS_2024_02_05
      - name: CALIFORNIA_VOTER_HISTORY_2024_02_05
      - name: COLORADO_VOTERS_2023_11_30
      - name: CONNECTICUT_VOTERS_2023_10_12
      - name: CONNECTICUT_VOTERS_2023_10_12_UNPARSED
      - name: DELAWARE_VOTERS_2023_11_17
      - name: DISTRICT_OF_COLUMBIA_RAW_DATA_2023_03_10
      - name: FLORIDA_VOTERS_2023_08_08
      - name: FLORIDA_VOTER_HISTORY_2023_08_08
      - name: GEORGIA_VOTERS_2023_09_13
      - name: GEORGIA_VOTER_HISTORY
      - name: IDAHO_VOTERS_2023_10_26
      - name: IOWA_VOTERS_2023_12_14
      - name: IOWA_VOTER_HISTORY_2023_12_14
      - name: KANSAS_VOTERS_2023_11_06
      - name: LOUISIANA_RAW_DATA_2023_11_23
      - name: MARYLAND_VOTERS_2023_12_05
      - name: MARYLAND_VOTER_HISTORY_2023_12_05
      - name: MICHIGAN_VOTERS_2023_11_21
      - name: MICHIGAN_VOTER_HISTORY_2023_11_21
      - name: MISSISSIPPI_RAW_DATA_2023_12_11
      - name: MISSISSIPPI_VOTER_HISTORY_2023_12_11
      - name: MISSOURI_VOTERS_2023_10_10
      - name: MONTANA_VOTERS_2023_11_06
      - name: MONTANA_VOTER_HISTORY_2023_11_06
      - name: NEBRASKA_VOTERS_2023_11_01
      - name: NEVADA_VOTERS_2023_07_31
      - name: NEVADA_VOTER_HISTORY_2023_07_31
      - name: NEW_HAMPSHIRE_VOTERS_2023_12_04
      - name: NEW_HAMPSHIRE_VOTER_HISTORY_2023_12_04
      - name: NEW_JERSEY_VOTERS_2023_11_24
      - name: NEW_JERSEY_VOTER_HISTORY_2023_11_24
      - name: NEW_MEXICO_RAW_DATA_2023_11_17
      - name: NEW_YORK_VOTERS_2023_09_20
      - name: NORTH_CAROLINA_VOTERS_2023_07_21
      - name: OHIO_VOTERS_2023_09_25
      - name: OKLAHOMA_VOTERS_2023_09_23
      - name: OKLAHOMA_VOTER_HISTORY_2023_09_23
      - name: OREGON_VOTERS_2023_11_01
      - name: PENNSLYVANIA_VOTER_HISTORY_2023_11_13
      - name: PENNSYLVANIA_VOTERS_2023_11_13
      - name: RHODE_ISLAND_VOTERS_2023_11_16
      - name: RHODE_ISLAND_VOTER_HISTORY_2023_11_16
      - name: SOUTH_CAROLINA_VOTERS_2024_01_04
      - name: SOUTH_DAKOTA_VOTERS_2023_11_06
      - name: TENNESSEE_VOTERS_2024_01_01
      - name: TEXAS_PROCESSED_DATA_2023_11_28
      - name: UTAH_VOTERS_2023_11_06
      - name: UTAH_VOTER_HISTORY_2023_11_06
      - name: VERMONT_VOTERS_2023_09_27
      - name: VIRGINIA_VOTERS_2023_11_17
      - name: WASHINGTON_VOTERS_2023_09_01
      - name: WASHINGTON_VOTER_HISTORY_2023_09_01
      - name: WEST_VIRGINIA_VOTERS_2023_11_06
      - name: WEST_VIRGINIA_VOTER_HISTORY
      - name: WISCONSIN_VOTERS_2023_10_17
      - name: WISCONSIN_VOTER_HISTORY_2023_10_17
      - name: WYOMING_VOTERS_2023_11_14